# Generated by Django 5.0 on 2024-01-06 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='short_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre corto'),
        ),
    ]
