# Generated by Django 5.0 on 2024-01-06 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('trabajo', models.CharField(choices=[('1', 'Operaciones'), ('2', 'Reembolsos'), ('3', 'proveedores'), ('4', 'Tecnología'), ('5', 'Contabilidad')], max_length=1, verbose_name='Trabajo')),
                ('imagen', models.ImageField(upload_to=None, verbose_name='Imagen')),
            ],
        ),
    ]
