# Generated by Django 5.0 on 2024-01-06 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
        ('departamento', '0002_alter_departamento_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='departamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='departamento.departamento', verbose_name='Cargo del empleado'),
        ),
    ]
